---
title: Handling Portlet Phases
order: 3
layout: page
---

= Handling Portlet Phases

Portlet specification deals with requests and responses; portlets receive render requests, action requests, resource requests, and more.
This request-centric approach is not immediately compatible with the types of applications you build with Vaadin - modern, dynamic applications.
So in order to operate seamlessly in the portlet environment, Vaadin Portlet support offers both the means to hook into these state changes as well as shorthands to perform portlet tasks in a more idiomatic Vaadin way.

== Portlet Requests and Phases

The portlet model operates on https://portals.apache.org/pluto/v301/portlet-api.html[phases] which do not mesh naturally with Vaadin.
Normally, the phase request contain data that the user might be interested in but since it makes little sense for a Vaadin Portlet to handle such requests, listeners were introduced.
In this section we take a look at different listeners, which allows Vaadin Portlets to hook into the different phases while operating within the UI thread of their Vaadin application.

=== Listeners
As described in <<creating-vaadin-portlets#,Creating Vaadin Portlets>>, the Vaadin Portlet consist of two parts: a class extending `VaadinPortlet` and a class extending Vaadin `Component`.
Vaadin Portlet support offers various listeners which allows implementing view component to react to updates from the portal.
To add an listener, your view should first implement `VaadinPortletEventView`.
Then in `VaadinPortletEventView.onPortletEventContextInit`, you have access to `VaadinPortletEventContext` which allows you to add the listeners you need.

The available listeners are:

- `PortletModeListener`
- `WindowStateListener`
- `PortletEventListener` (part of the <<inter-portlet-communication#,Inter-Portlet Communication>>)

Next, we will have a look at the listeners which enable the view component react to changes to the portlet's state.

==== `PortletModeListener`

Portlets can operate in different modes.
The standard modes in the portlet specification are `View`, `Edit`, and `Help`.
User of the portlet can change these modes using the controls on the portlet window, or through the portlet API.

React to changes to the portlet mode by adding a `PortletModeListener` to `VaadinPortletEventContext` class:

[source,java]
----
public class MyPortletView extends Div implements VaadinPortletEventView {
    @Override
    public void onPortletEventContextInit(VaadinPortletEventContext context) {
        context.addPortletModeChangeListener(event -> showHelpText(event.isHelpMode()));
    }
}
----

The type of `event` object is `PortletModeEvent` which contains information like the portlet mode, the previous portlet mode, and helpful shorthands for accessing the most commonly needed properties.

==== `WindowStateListener`

A portlet window have different sizes, or window states.
The standard states in the portlet specification are `Normal`, `Maximized`, and `Minimized`.
User of the portlet can change these states using the controls on the portlet window, or through the portlet API.

React to changes to the window states by adding a `WindowStateListener` to `VaadinPortletEventContext` class:

[source,java]
----
public class MyPortletView extends Div implements VaadinPortletEventView {
    @Override
    public void onPortletEventContextInit(VaadinPortletEventContext context) {
        context.addWindowStateChangeListener(event -> showDetailsField(event.isMaximized()));
    }
}
----

The type of `event` object is `WindowStateEvent` which contains the information about the window state and helpful shorthands for accessing the most commonly needed properties.

==== Listeners Invocation Order

In some cases, you may want to have a component class with several listeners.
Vaadin Portlet support calls each listener only once per portlet request and in the following order.

1. `PortletModeListener`
2. `WindowStateListener`
3. `EventListener`

=== Changing the Portlet States from Java

In addition to handling the different state changes originating from the client-side, you can also invoke the same changes from the Java code.
This is done by using the API provided by the `VaadinPortlet`, or calling the same methods on your own portlet class extending `VaadinPortlet`.

You can change the portlet mode of the portlet by calling:

[source,java]
----
// for the current portlet that is processing requests
VaadinPortlet.getCurrent().setPortletMode(PortletMode.EDIT);
----

Similarly, portlet window state can be changed by calling:

[source,java]
----
// for the current portlet that is processing requests
VaadinPortlet.getCurrent().setWindowState(WindowState.MAXIMIZED);
----

=== Example of a Vaadin Portlet Reacting to and Changing States

This is a full example with two class, `MyPortlet` (a portlet class) extending `VaadinPortlet` and `MyView` extending `Div` (a view class).
The view class implements `VaadinPortletEventView`.

`MyView` reacts to the status changes by updating the text of a `Paragraph`, informing the user whether the portlet mode or the window state changed.
The example also shows how the developer can change portlet mode and window state from the Java code.
The view contains two buttons.
One with "Maximize" text changes the window state of the portlet to `MAXIMIZED`, and the other with "Show help" text sets the portlet mode to `HELP`.

.MyPortlet.java
[source,java]
----
public class MyPortlet extends VaadinPortlet<MyView> {

}
----

.MyView.java
[source,java]
----
public class MyView extends Div implements VaadinPortletEventView {

    private Paragraph stateInformation;

    public MyView() {
        stateInformation = new Paragraph("Use the portlet controls or the "
                + "buttons below to change the portlet's state!");

        Button maximizeButton = new Button("Maximize", event -> VaadinPortlet
                .getCurrent().setWindowState(WindowState.MAXIMIZED));

        Button helpButton = new Button("Show help", event -> VaadinPortlet
                .getCurrent().setPortletMode(PortletMode.HELP));

        add(stateInformation, maximizeButton, helpButton);
    }

    @Override
    public void onPortletEventContextInit(VaadinPortletEventContext context) {
        context.addWindowStateChangeListener(event -> stateInformation
                .setText("Window state changed to " + event.getWindowState()));
        context.addPortletModeChangeListener(event -> stateInformation
                .setText("Portlet mode changed to " + event.getPortletMode()));
    }
}
----

=== Using Handler interfaces

There is another way to listen to changes in window state and portlet mode.
In this way, instead of `VaadinPortletEventView`, your view should implement `WindowStateHandler` and/or `PortletModeHandler` interfaces.
The following example shows how to react to changes to window state using `WindowStateHandler` interface and changes to portlet mode using `PortletModeHandler` interface.

[source,java]
----
public class MyView extends Div
        implements PortletModeHandler, WindowStateHandler {

    private Paragraph stateInformation = new Paragraph();

    public MyView() {
        add(stateInformation);
    }

    @Override
    public void portletModeChange(PortletModeEvent event) {
        stateInformation
                .setText("Portlet mode changed to " + event.getPortletMode());
    }

    @Override
    public void windowStateChange(WindowStateEvent event) {
        stateInformation
                .setText("Window state changed to " + event.getWindowState());
    }
}
----
