---
title: Executing JavaScript
order: 2
layout: page
---

= Executing JavaScript

You can use server-side Java to execute simple JavaScript snippets in the browser.
You can also pass parameters to the executed script as variables named $0, $1 and so on.
The framework automatically serializes and escapes the parameter values.

[source,java]
----
public static void logElementSize(String name, Element element) {
    Page page = UI.getCurrent().getPage();

    page.executeJs(
            "console.log($0 + ' size:', $1.offsetWidth, $1.offsetHeight)",
            name, element);
}
----

Supported parameter types are `String`, `Boolean`, `Integer`, `Double`, `JsonValue` and `Element`.
The script is executed after the DOM tree has been updated based on server-side changes.
The parameter value will be `null` for an element parameter that is not attached after the update (according to the server-side DOM).

[NOTE]
The script is executed asynchronously, so `executeJs` cannot directly return the result of the execution. Instead, the returned `PendingJavaScriptResult` instance can be used to add a callback that is run when the result is available. 

There is already ready made solution for listening browser window resize events
from the server side without custom JavaScript execution, 
see <<tutorial-flow-window-resize#,Browser Window Resize Events>>.
