---
Title: Migration Strategies
Order: 2
Layout: page
---

= Migration Strategies

For any existing Vaadin 8 or 7 application it might be desirable to extend the lifetime of the application and make it possible to add new features using Vaadin 10. The need for migration is always application and business specific. There are several options you should consider.

== Use Vaadin Eight - It Is Great!

You can stay with Vaadin 8. We are going to maintain it at least until 2022. That gives you the option to plan your migration longer term, and consider what is the needed lifetime for your application. You should look at the needs of your users and how those needs and the technologies used evolve during that time.

Internet Explorer 11 support is still a critical thing for many applications, and for IE11 Vaadin 8  might offer better performance than Vaadin 10 since polyfills are needed with IE 11. During the guaranteed lifetime of Vaadin 8 the usage of IE11 should decrease significantly from what it is now.

During the remaining years of Vaadin 8 support, the quarterly Vaadin platform releases will bring more and more features that you can start using when you eventually decide to migrate to Vaadin 10 or start building a new application with fresh design.

== Using the Multiplatform Runtime for Running V8 Application Inside V10

The Multiplatform Runtime makes it possible to run view and components from your Vaadin 8 application inside Vaadin 10. This helps you migrate it to V10 bit by bit, or just incrementally add V10 features.

Using the runtime you will be able to get your V8 App running in V10 after couple of quick steps. Then you can migrate the necessary parts while having a working application after each step.


== Transform Existing Application To Vaadin 10

Transforming a Vaadin 8 app to Vaadin 10 by: reusing backend interaction, business logic, as much as possible of UI logic, but building the UI with brand new components. When planning this migration, you should at a minimum read through all of this documentation to understand the differences and verify what features are available and what you need to redesign. One big benefit is that the Data APIs, `Binder` and `DataProvider` work the same way in V10, so you won’t have to rework your backend integration.

Vaadin is also offering a service for doing the migration assessment for your Vaadin 8 or 7 application. Our assessment will help you understand what a transformation would entail and will give you an indication on the amount of work needed. You can also get us to do the migration for you.

== Fresh Start by Redesigning Application for Vaadin 10

Sometimes the best approach is to start from fresh - this way you will be able to focus on using new V10 features to deliver value to your users, instead of carrying over legacy code. As mentioned in previous topic, there is still probably some opportunities to reuse existing solutions related to integration to your business logic and backend.
