---
Title: Routing and Navigation
Order: 4
Layout: page
---

= Routing and Navigation

Routing and navigation are core concepts for any web application or site. In Vaadin 10 this has been completely reinvented. The `Navigator` in Vaadin 8 and 7 only supported single-level navigation, had limited support for parameters and did not support the HTML5 History API until Vaadin 8.2.

This document only outlines the core concept and how if differers from the old `Navigator`. To get the best picture on the capabilities of the new `Router`, you should visit the [documentation](TODO LINK) for it.

The `Router` in Vaadin 10 is easy to use and allows building robust and complex application structures with hierarchies, error handling and view access control by using lifecycle events.

The routes are configured declaratively on each navigation target and are the same for the entire application, unlike in V8 where configuration was made for each UI instance separately:

[source,java]
----
@Tag("div")
@Route(value="company", layout=MainLayout.class)
public class CompanyComponent extends Component {
     // Implementation omitted
}
----

Thus, when migrating from using `Navigator`, any `View` from Vaadin 8 can migrated to V10 by removing the registration from the now optional `UI` class and instead applying the `@Route` annotation the class. *Note* that there is no `View` interface in V10, but instead the class must be a `Component`!

To receive an event when the user navigates to or from a view, make it implement one of `BeforeEnterObserver`, `BeforeLeaveObserver` or `AfterNavigationObserver` interfaces instead of the `enter` and `beforeLeave` methods from `View` in Vaadin 8. `BeforeLeaveEvent.postpone()` can be used to postpone or cancel navigation to achieve the same results as selectively calling `ViewBeforeLeaveEvent.navigate()` in Vaadin 8.

The `ViewDisplay` concept is replaced in V10 with the `RouterLayout` interface, but now it is possible to do more than single-level hierarchies, by using the `@ParentLayout` annotation.

There is no `ViewProvider` in V10 as it is not needed.

With the HTML5 History API, it is possible to have deep-linking and use proper navigation state and parameters for the navigation targets. V10 even supports optional parameters. It is not anymore possible to use the fragment style (`#!`) navigation state from V8 as the fragment is not intended to be used on the server side at all, but just be a browser feature for navigation inside a page.

It is very much recommended to take a look at the `Router` [documentation](TODO LINK) to get full understanding on how to structure your V10 application.
