---
title: Differences between npm and pnpm
order: 16
layout: page
---

ifdef::env-github[:outfilesuffix: .asciidoc]

= Differences Between pnpm and npm

Starting from Vaadin 14.2 _pnpm_ (AKA _performant npm_) can be used as the frontend package manager instead of _npm_.
https://pnpm.js.org/[pnpm] uses a shared repository for all projects in a system which allows to reduce
packages download time. On the contrast, by default npm will download all dependencies again for every project.

If pnpm is not installed globally the framework will install it locally to `{home_folder}/.vaadin`.
The `package-lock.json` file which is used by npm is incompatible with pnpm and it's
removed automatically if pnpm is used. pnpm uses `pnpm-lock.yaml`
file instead of `package-lock.json`. This means that any custom dependency configurations
should go to `pnpm-lock.yaml`.

Starting from Vaadin 14.2 (and 15), regardless if npm or pnpm is used, the `package.json` will contain all the package information
and `target/frontend/package.json` referenced by the `@vaadin/flow-deps` dependency does not exist anymore. The `@vaadin/flow-deps`
is removed automatically from the `package.json` dependencies.

The framework dependency handling uses a `"vaadin"` object inside `package.json` and only touches dependencies named there.

== Switching Between pnpm and npm

By default Vaadin 14.2 and 15 projects uses npm. Switching between pnpm / npm is possible
by setting the `pnpm.enable` configuration property value to `true` or `false` respectively (`false` is the default).
This property can be applied using either system properties (NOTE: use prefix `vaadin.` when using system properties),
servlet initialization parameters, or Spring application properties.
To read more about how to set properties, see the
<<tutorial-flow-runtime-configuration#, Application runtime configuration documentation>>.

Alternatively, the property can be also set to the `vaadin-maven-plugin`, using `pnpmEnable`.

[source,xml]
----
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <version>${project.version}</version>
    <configuration>
        <pnpmEnable>true</pnpmEnable>
    </configuration>
</plugin>
----
