---
title: Embedded Application in Production
order: 5
layout: page
---

ifdef::env-github[:outfilesuffix: .asciidoc]

= Embedded Application in Production

Embedding Vaadin applications in production mode requires two steps:

* Package application for production in the normal way
* Import the packaged application onto the target page

For the first step see the general information about production mode which is available in 
<<../production/tutorial-production-mode-basic#,Taking your Application into Production>> 
tutorial.

The second step differs a bit from the application in dev mode. As you can 
see two lines of code are used to import an embedded application in the 
<<tutorial-webcomponent-exporter#,Embedding a Flow Application>> tutorial:

[source, html]
----
<script type='text/javascript' src='/frontend/bower_components/webcomponentsjs/webcomponents-loader.js'></script>
<link rel='import' href='/vaadin/web-component/login-form.html'>
----

The first line loads a polyfill library for browsers that do 
not have native support for `rel="import` on a `link` element.

In the production mode this library is in a different folder which depends
on the browser. To be able to avoid this boilerplate line in the production 
mode you should just use `script` tag for the web component instead of `link`:

[source, html]
----
<script type='text/javascript' src='/vaadin/web-component/login-form.html'></script>
----

In production mode the generated `login-form.html` content is just a JavaScript code
which adds a proper polyfill library for your along with the required imports.
