---
title: Embedded Application in Production
order: 5
layout: page
---

ifdef::env-github[:outfilesuffix: .asciidoc]

= Embedded Application in Production

The general information about production mode is available in <<../production/tutorial-production-mode-basic#,Taking your Application into Production>> tutorial.

Just package the embedded application for production and you may use it in
an embedding application.

The only thing you should be aware of is the web component import into 
your embedding application page.

As you can see two lines of code are used to do it in the 
<<tutorial-webcomponent-exporter#,Embedding a Flow Application>> tutorial:

[source, html]
----
<script type='text/javascript' src='/frontend/bower_components/webcomponentsjs/webcomponents-loader.js'></script>
<link rel='import' href='/vaadin/web-component/login-form.html'>
----

The first line loads polyfills library which allows to handle properly the second line 
 `link` import tag in the browsers that don't support it.
The library is available as a part of embedded Vaadin application and you 
should just take care about proper path to it.

In the production mode this library is in a different folder which depends
on the browser. To be able to avoid this boilerplate line in the production 
mode you should just use `script` tag for the web component instead of `link`:

[source, html]
----
<script type='text/javascript' src='/vaadin/web-component/login-form.html'></script>
----

In production mode the generated `login-form.html` content is just a JavaScript code
which adds a proper polyfill library for your along with the required imports.
