---
title: Embedded Application Push Configuration
order: 4
layout: page
---

ifdef::env-github[:outfilesuffix: .asciidoc]

= Embedded Application Push Configuration

You may configure and enable Push in your embedded application.
See Server Push Configuration (<<../advanced/tutorial-push-configuration#,>>) tutorial 
for Push overview.

There are two ways to configure Push for the embedded application: use 
`@Push` annotation for your `WebComponentExporter` class or declare it
on the servlet level. You can see how to do it on the servlet level in the
mentioned tutorial.

Similarly to declaring `@Theme` annotation described in 
<<tutorial-webcomponent-theming#,7.6. _Theming an Embedded Application_>> tutorial, 
you may declare `@Push` annotation for `WebComponentExporter` class:

[source, java]
----
@Push
public class PushComponentExporter
        extends WebComponentExporter<Div> {
----

`@Push` annotation declaration has the same limitation as `@Theme` annotation:
it's not possible to declare several different `@Push` annotations for different
exporter classes. An exception will be thrown otherwise during the application
startup. It's enough to configure Push only for one exporter.
