---
title: Offline experience
order: 6
layout: page
---

= Offline experience

Flow will automatically serve generated offline page. The generated offline page
is simple page tell that application is offline and it requires network connection.

Page is personalized with given name and icon.

== Custom offline page

To use own offline page create file with name "*offline.html*" in webapp -folder.

```
src/main/webapp/offline.html
```

To change the name of the file, use `@PWA` -property *offlinePath*.

Offline page may only use resources found in cache. By default, in cache
there’s only the offline page, manifest and icons. If offline page needs other
resources (such as css, images, webcomponents) describe those in offlineResources.

Offline experience with simple fallback page is very limited and by having separate
offline page it also isolates the offline experience from application itself.
For this developer could have offline experience within web components and
re-use those web components in offline -page.
