---
title: Application Icons
order: 3
layout: page
---

= Application Icons

Icons are needed to give fav-icon for browser page, icon for device for installed apps and
also to create splash screen for installed applications. By default, Flow will
use a default icon and serve it automatically.

== Using a custom icon

To customize the application images, copy your image to the following location:
```
src/main/webapp/icons/icon.png
```

Flow will automatically scan for an *icon.png* icon file from the */icons* folder
inside the webapp resources folder. The icon should be in png format. Flow will
automatically create different sizes of images from the given image for different
devices. If no icon is found, then Flow will fall back to default image.

A given image is resized to different sizes for different use cases, so use an image
with size of at least 512x512. The icon will be automatically resized - only
downscaling the image, which is the reason to give a big enough image - to different
sizes, using the top-left -pixel as background color if needed.

== Overriding the generated icons

All the generated images are named as "*icons/icon-[width]x[height].png*".

To override the generated image, place an image named as the created one to the web application
resources folder.

For example, for getting a custom splash screen for hi-res iOS devices,
create an image of size 1125x2436 and copy it to:
```
src/main/webapp/icons/icons/icon-1125x2436.png
```

== Renaming the icons

To change the used icon path give a custom path in `@PWA` -annotation property *iconPath*.

Example
```
@PWA(name = "My Progressive Web Application", shortname = "MyPWA", iconPath = "img/icons/logo.png")
```

Then place the icon to:
```
src/main/webapp/img/icons/logo.png
```

Now all icons will be named using the value in *iconPath*, so a 512x512 sized icon
would be "*img/icons/logo-512x512.png*".
