---
title: Application Icons
order: 3
layout: page
---

= Application Icons

Icons are needed to give fav-icon for browser page, icon for device for installed apps and
also to create splash screen for installed applications. By default, Vaadin will
use a default icon and serve an it automatically.

== Using a custom icon

To customize the application images, copy your image to the following location
```
src/main/webapp/icons/icon.png
```

Vaadin will automatically scan for an *icon.png* icon file from the */icons* folder
inside the webapp resources folder. The icon should be in png format. Vaadin will
automatically create different sizes of images from the given image for different
devices. If no icon is found, then Vaadin will fall back to default image.

Given image is resized to different sizes for different use cases, so use image
with size of at least 512x512. The icon will be automatically resized - only
downscaling the image, that's the reason to give big enough image - to different
sizes, using top-left -pixel as background color if needed.

== Overriding the generated icons

All the generated images are named with as "*icons/icon-[width]x[height].png*".

To override generated image place image named as created one to web application
resources folder.

For example, for getting a custom splash screen for hi-res iOS devices,
create an image of size 1125x2436 and copy it to:
```
src/main/webapp/icons/icons/icon-1125x2436.png
```

== Renaming the icons

To change the used icon path give custom path in `@PWA` -annotation property *iconPath*.

Example
[source,java]
----
@PWA(name = "My Progressive Web Application",
     shortName = "MyPWA",
     iconPath = "img/icons/logo.png")
----

Then place the icon to
```
src/main/webapp/img/icons/logo.png
```

Now all icons will be named using value in *iconPath*, so 512x512 sized icon
would be "*img/icons/logo-512x512.png*".
