---
title: Setup Live Reload using JRebel
order: 7
layout: page
---

= Setup Live Reload using JRebel

Live Reload works with JRebel allowing for code changes to affect Vaadin applications in real time, skipping rebuilds and redeploys.
More information about JRebel is available at https://www.jrebel.com/products/jrebel.

== Step-by-step guide

. Setup and activate JRebel in your favourite IDE by following the Quick Start guides available at https://www.jrebel.com/products/jrebel/learn
. In your `pom.xml` create a new development build profile and add `flow-jrebel-plugin` as an artifact to this profile, like so:
+
----
<profiles>
       <profile>
           <id>development</id>
           <activation>
               <activeByDefault>true</activeByDefault>
           </activation>
           <dependencies>
               <dependency>
                   <groupId>com.vaadin</groupId>
                   <artifactId>flow-jrebel-plugin</artifactId>
                   <version>3.1-SNAPSHOT</version>
               </dependency>
           </dependencies>
       </profile>
       ...
   </profiles>
----
+
[NOTE]
====
Since JRebel it's not tipically used in production, this profile is created in order to avoid packaging `flow-jrebel-plugin` into the production war file.
====
. Run your Vaadin application using the JRebel Agent
. Navigate to your Vaadin application on the browser, make and save some changes, and the browser will reload automatically

== Known issues

* At the moment, running a Vaadin application with JRebel might cause some related exceptions to be logged on the console. These can be safely ignored as no unexpected behavior will affect your application. These exeptions look like this:
+
----
JRebel: ERROR Class 'com.vaadin.flow.server.startup.RouteRegistryInitializer' could not be processed by org.zeroturnaround.jrebel.vaadin.cbp.RouteRegistryInitializerCBP@org.eclipse.jetty.webapp.WebAppClassLoader@139f1a94: org.zeroturnaround.bundled.javassist.CannotCompileException: [source error] getInstance(javax.servlet.ServletContext) not found in com.vaadin.flow.server.startup.ApplicationRouteRegistry
	at org.zeroturnaround.bundled.javassist.CtNewMethod.make(SourceFile:84)
	at org.zeroturnaround.bundled.javassist.CtNewMethod.make(SourceFile:50)
	at org.zeroturnaround.bundled.javassist.CtMethod.make(SourceFile:140)
  ...
----
