---
title: Overview
order: 1
layout: page
---

include::../themes-shared.asciidoc[opts=optional]

= Overview

Material is a theme inspired by the https://material.io[Material Design guidelines].

The core Material package defines the basic building blocks for component themes as CSS custom properties, also known as design tokens, such as colors, typography and other visual styles.

== Getting started

=== Install

The Material theme comes bundled with Vaadin, including all individual components. If you need, you can also install the core Material package separately from https://www.npmjs.com[npm].

[source,terminal]
----
npm i @vaadin/vaadin-material-styles
----

=== Import and Include Style Sheets

The global style sheets, which define the global custom properties (a.k.a. design tokens) and define basic color and typography rules, are automatically included in your Vaadin app when you are using Material as your theme.

You can import and include these style sheets manually if needed, for example if you are building a client-side only app.


.`Java`
[source,java]
----
@Route("")
@Theme(Material.class)
public class MaterialApp extends Div {
}
----

.`JavaScript`
[source,javascript]
----
// Import the main style sheets which set global font styles and colors
import '@vaadin/vaadin-material-styles/color.js';
import '@vaadin/vaadin-material-styles/typography.js';

// Import the <custom-style> element from Polymer and include the style sheets in the global scope
import '@polymer/polymer/lib/elements/custom-style.js';
const style = document.createElement('custom-style');
style.innerHTML = `<style include="material-color material-typography"></style>`;
document.head.appendChild(style);

// Import a theme-specific component, for example <vaadin-button>
import '@vaadin/vaadin-button/theme/material/vaadin-button.js';
----

See <<../../flow/theme/including-style-sheets#,Including style sheets>> for more information
