---
title: Built-in themes
order: 2
layout: page
---

= Built-in themes

Vaadin comes with a set of built-in themes which you can choose from. See https://vaadin.com/themes[vaadin.com/themes] for a high-level overview of theming in Vaadin.

== Lumo

The default theme for Vaadin apps. If you do not explicitly choose a theme, Lumo will be used. See the <<../../components/foundation/lumo#,Lumo theme docs>> for all the details regarding it.

.`Java`
[source,java]
....
@Route("")
@Theme(Lumo.class)
public class LumoApp extends Div {
}

// or

@Route("")
public class LumoApp extends Div {
}
....

.`JavaScript`
[source,javascript]
....
// Import the main style sheets which set global font styles and colors
import '@vaadin/vaadin-lumo-styles/color.js';
import '@vaadin/vaadin-lumo-styles/typography.js';

// Import the <custom-style> element from Polymer and include the style sheets in the global scope
import '@polymer/polymer/lib/elements/custom-style.js';
const style = document.createElement('custom-style');
style.innerHTML = `<style include="lumo-color lumo-typography"></style>`;
document.head.appendChild(style);

// Import a theme-specific component, for example <vaadin-button>
import '@vaadin/vaadin-button/theme/lumo/vaadin-button.js';

// The default component import uses Lumo as well
import '@vaadin/vaadin-button/vaadin-button.js';
....

== Material

A theme inspired by the https://material.io[Material Design guidelines]. See the <<../../components/foundation/material#,Material theme docs>> for all the details regarding it.

.`Java`
[source,java]
....
@Route("")
@Theme(Material.class)
public class MaterialApp extends Div {
}
....

.`JavaScript`
[source,javascript]
....
// Import the main style sheets which set global font styles and colors
import '@vaadin/vaadin-material-styles/color.js';
import '@vaadin/vaadin-material-styles/typography.js';

// Import the <custom-style> element from Polymer and include the style sheets in the global scope
import '@polymer/polymer/lib/elements/custom-style.js';
const style = document.createElement('custom-style');
style.innerHTML = `<style include="material-color material-typography"></style>`;
document.head.appendChild(style);

// Import a theme-specific component, for example <vaadin-button>
import '@vaadin/vaadin-button/theme/material/vaadin-button.js';
....


== No theme

If you want to control all styling manually you can opt-out of loading any built-in theme.

.`Java`
[source,java]
....
@Route("")
@NoTheme
public class UnthemedApp extends Div {
}
....

.`JavaScript`
[source,javascript]
....
// Import a component without presentational styles
import '@vaadin/vaadin-button/src/vaadin-button.js';
....


== Limitations

It is not possible to switch themes at runtime. A full page reload is required.

It is not possible to mix themes. For example, you can't use the Lumo theme for Date Picker and the Material theme for Button at the same time, because Date Picker internally uses the Button component.
