---
title: Integrating Your Own Component Theme
order: 5
layout: page
---

= Integrating Your Own Component Theme

To create your own component theme to be used with the wrapped Vaadin components
you need to create a theme class that informs flow how to translate the base un-themed
component html import to use your themed version.

The `getBaseUrl` should return the part of the htmlImport that can be used to determine if
it is an import that could be changed to a theme import. (for Vaadin components that is `/src/`)

The `getThemeUrl` should return what the base url part should be changed to to get the
correct theme import. (for Vaadin components that `/theme/[themeName]` is used)

[source,java]
----
@JsModule("@vaadin/vaadin-lumo-styles/color.js")
public class MyTheme implements AbstractTheme {
    @Override
    public String getBaseUrl() {
        return "/src/";
    }

    @Override
    public String getThemeUrl() {
        return "/theme/myTheme/";
    }
}
----

For more control there is `getBodyInlineContents()` that returns a collection of html
that will be inlined to the BootstrapPage body. For instance, it can be used to add a
custom style to have the correct typography:
[source,java]
----
@Override
public List<String> getHeaderInlineContents() {
    return Collections.singletonList("<custom-style>\n"
            + "    <style include=\"lumo-color lumo-typography\"></style>\n"
            + "</custom-style>");
}
----

Your theme can also support variants. For instance, Lumo theme supports both light and dark variants.
To add support for variants, you can override the `getBodyAttributes`  method:
[source,java]
----
@Override
public Map<String, String> getBodyAttributes(String variant) {
  if ("dark".equals(variant)) {
    // the <body> element will have the "theme" attribute set to
    // "dark" when the dark variant is used
    return Collections.singletonMap("theme", "dark");
  }
  return Collections.emptyMap();
}
----

Then you need to create the themed `.js` files for the elements in the `/frontend/theme/myTheme/element-name.js`

== Creating Your Own Component Theme

The theming for the Vaadin components is built using `Vaadin.ThemableMixin`.
See link:https://github.com/vaadin/vaadin-themable-mixin/wiki[vaadin-themable-mixin wiki] to learn how theming of Vaadin components is done.
