---
title: Theming Crash Course
order: 4
layout: page
---
= Theming Web Components

This chapter gives an overview of everything you need to understand in order to master and be productive in theming modern web applications which are built with web components.

First, it is important to draw the line between global styles and scoped styles:

* Before web components were introduced, the styles were global on the web, meaning that a selector in CSS can target any element in the document.
* Web components, and Shadow DOM in particular, introduce style scoping to the web platform.
The contents of web components are isolated from global styles, and instead have scoped styles, which are specific to a particular web component only.

This guide describes how to apply global and scoped styles, as well as how to share common styles between style scopes for the application theming purpose.

== Global Styles

Global styles are styles defined in the document scope.
Global styles can target document body and any regular DOM contents inside, including the application views,
but can not target Shadow DOM contents, such as internals of Vaadin components, Polymer templates, and other web components.

To define global styles, we need to wrap our CSS in `<custom-style><style>...</style><custom-style>` HTML tags.
This is required by Polymer to enable correct cross-browser scoping.

The problem is that we cannot import directly `.html`, thus we will write `.css` files and instruct Flow to wrap it
in HTML tags via annotations.


.frontend/styles/shared-styles.css
[source,css]
----
/* Example global style */
html {
  font-size: 1em;
}
----

.MyApplication.java
[source,java]
----
@Route(value = "")
@CssImport("./styles/shared-styles.css")
public class MyApplication extends Div {
}
----


== Styling Polymer Templates

Since Polymer templates are web components, their template contents end up in Shadow DOM.
By design, Shadow DOM defines a local style scope, isolated from global styles.

Scoped styles, which are specific to a single template, can be added directly to the `<style>` tag inside the template getter:

.frontend/src/my-view.js
[source,js]
----
import { PolymerElement } from '@polymer/polymer/polymer-element.js';
import { html } from '@polymer/polymer/lib/utils/html-tag.js';

class MyView extends PolymerElement {
  static get template() {
    return html`
      <style>
        /* Example scoped styles, applied to <my-view> template contents only */
        :host {
          /* Styles for the `<my-view>` hosting element */
          display: block;
        }

        .my-view-title {
          font-weight: bold;
          border-bottom: 1px solid gray;
        }
      </style>

      <div class="my-view-title">My view title</div>
    `;
  }
}
customElements.define('my-view', MyView);
----


I you'd rather have `.css` file you can import and use it in your template in this way:

.frontend/src/my-view.css
[source,css] 
----
:host {
  /* Styles for the `<my-view>` hosting element */
  display: block;
}

.my-view-title {
  font-weight: bold;
  border-bottom: 1px solid gray;
}
----

.frontend/src/my-view.js
[source,js]
----
import { PolymerElement } from '@polymer/polymer/polymer-element.js';
import { html } from '@polymer/polymer/lib/utils/html-tag.js';
import styles from './my-view.css'

class MyView extends PolymerElement {
  static get template() {
    return html`
      <style> ${styles} </style>

      <div class="my-view-title">My view title</div>
    `;
  }
}
customElements.define('my-view', MyView);
----

== Using Custom CSS Properties

One of the needs for theming is to share common style values, such as sizes, colors, etc, between pieces of the application.
This could be achieved using custom CSS properties, which is a special syntax for assigning and referencing CSS variables.
Custom CSS properties are inherited, their values cross Shadow DOM boundaries.
Polymer templates can reuse values defined by global styles, as well as override them.

Use global styles for `html` element to define a global custom CSS property:


./frontend/styles/shared-styles.css
[source,css] 
----
html {
  /* Example global custom CSS property definition */
  --my-theme-color: brown;
}
----

For referencing your custom CSS property, use ```var(--my-property)``` syntax. For example, in your Polymer template styles:

.frontend/src/my-view.css
[source,css] 
----
.my-view-title {
  /* Example referencing custom CSS property */
  color: var(--my-theme-color);
}
----

== Using Style Modules

Style modules allow sharing the same stylesheet between multiple Polymer templates and global styles.

Style modules are defined in HTML using ```<dom-module id="my-styles"><template><style>/* ... */</style></template></dom-module>``` tag combination.

Therefore when you import it in the application you need to assign an unique name for the module id.

.frontend/styles/shared-styles.css
[source,css]
----
/* Example style module */
.my-outline-style {
  outline: 1px solid green;
}
----

.MyApplication.java
[source,java]
----
@Route(value = "")
@CssImport("./styles/shared-styles.css", id = "shared-styles")
public class MyApplication extends Div {
}
----

To include a style module in a Polymer template, specify the same `id` value in the wrapping `<style>` block.

.frontend/src/my-view.js
[source,js]
----
import { PolymerElement } from '@polymer/polymer/polymer-element.js';
import { html } from '@polymer/polymer/lib/utils/html-tag.js';
import styles from './my-view.css'

class MyView extends PolymerElement {
  static get template() {
    return html`
      <style include="shared-styles"> ${styles} </style>

      <div class="my-view-title">My view title</div>
    `;
  }
}
customElements.define('my-view', MyView);
----


NOTE: Use a space-separated list of style module ids to include multiple style modules into a single scope: ```<style include="shared-styles other-shared-styles"></style>```.

Style modules can also be included when importing other styles.

.MyApplication.java
[source,java]
----
@Route(value = "")
@CssImport("./styles/specific-styles.css", include = "shared-styles")
public class MyApplication extends Div {
}
----
