---
title: Theming basics
order: 5
layout: page
---

= Theming basics

Learn the basics of customizing the built-in themes with CSS. To learn how to theme and style Vaadin components, see <<styling-vaadin-components#,Styling Vaadin Components>>.

=== Prerequisites

You should be familiar <<including-style-sheets#,how to include style sheets>> for the global scope and for component scopes, where you can write your CSS. <<themes-and-styling#prerequisites,Basic understanding of CSS>> is also required.

== Fonts and colors

The most common theme customization is to adjust the global font and color properties.

=== Lumo theme

.`styles/global.css`
[source,css]
....
html {
  --lumo-font-family: Arial, Helvetica, sans-serif;
  --lumo-primary-text-color: hsl(265, 88%, 44%);
  --lumo-primary-color: hsl(265, 90%, 52%);
  --lumo-primary-color-50pct: hsla(265, 90%, 52%, 0.5);
  --lumo-primary-color-10pct: hsla(265, 90%, 52%, 0.1);
}
....

See the <<../../components/foundation/lumo#,Lumo theme>> documentation for all of the available top-level properties, which affect all components.

==== Lumo theme editor

To quickly adjust most of the global styles of Lumo, you can use the https://demo.vaadin.com/lumo-editor/[Lumo theme editor].

The Lumo theme editor is not yet an officially supported tool and does not necessarily support the latest versions of Vaadin. You can still use the CSS it produces by copying it to the correct files in your project.

=== Material theme

.`styles/global.css`
[source,css]
....
html {
  --material-font-family: Arial, Helvetica, sans-serif;
  --material-primary-text-color: hsl(265, 88%, 44%);
  --material-primary-color: hsl(265, 90%, 52%);
}
....

See the <<../../components/foundation/material#,Material theme>> documentation for all of the available top-level properties, which affect all components.
