---
title: Theming Components - Overlay
order: 6
layout: page
---

= Theming Components - Overlay

`<vaadin-overlay>` is a Web Component for creating overlays. It is an essential part of many components such as:

* `dialog`
* `notification`
* `combo-box`
* `date-picker`
* `time-picker`
* `select`
* `context-menu`

Those component are actually 2 components;

. The main component, e.g. `<vaadin-dialog>`, which is not visible (`display:none`).
. The overlay component, `<vaadin-dialog-overlay>`, which is actually visible.

== How to style an overlay

The `<vaadin-overlay>` component contains 3 stylable parts:

. *backdrop*: the optional modality curtain, covering the whole host/viewport.
. *overlay*: container for position/sizing/alignment of the content – this one is usually a scrolling container as well.
. *content*: the content area inside the scrolling container, where padding should be applied (if you want it to affect the bottom of scrolled content as well).

[WARNING]
Attributes from the main component are not copied to the overlay component, e.g. the class selector.

The theme attribute is an exception to the above, and it is copied to the overlay component, allowing styling of individual overlays.

To style an overlay component it is necessary to create a style CSS module, target the stylable parts, instruct flow to import it as a module targeting the specific component, and set the `theme` attribute to the main component in your view:

.frontend/styles/my-overlay-theme.css
[source,css]
----
:host([theme~="custom-theme-variant"]) [part~="overlay"]
{
}
----

.MyApplication.java
[source,java]
----
@Route(value = "")
@CssImport(value = "./styles/my-overlay-theme.css",
           themeFor = "vaadin-*-overlay")
public class MyApplication extends Div {
}
----

.MyView.java
[source,java]
----
public class MyView extends VerticalLayout {
    public MyView() {
        Dialog dialog = new Dialog();
        dialog.getElement().setAttribute("theme",
                "custom-theme-variant");
    }
}
----

If you want to be more specific, and target overlays of `vaadin-dialog`, do not use wildcards in the `themeFor` and target the `vaadin-dialog-overlay` element.

.frontend/styles/my-dialog-overlay-theme.css
[source,css]
----
[part="backdrop"] {
}
[part="overlay"] {
}
[part="content"] {
}
----


.MyApplicationWithDialog.java
[source,java]
----
@Route(value = "")
@CssImport(value="./styles/my-dialog-overlay-theme.css",
           themeFor = "vaadin-dialog-overlay")
public class MyApplicationWithDialog extends Div {
}
----

[NOTE]
ThemableMixin does not guarantee the order in which the style modules are applied.
It is important to declare CSS rules whose specificity is greater than the Lumo properties that are being overridden.
For more information refer to <<application-theming-basics#, Application Theming Basics >>.
