---
title: Importing HTML and JavaScript
order: 2
layout: page
---

= Importing HTML and JavaScript

You can add HTML imports and JavaScript to your host page directly from your Java classes. 
 
There are two ways to add HTML and JavaScript files. Both have the same effect and you can use whichever suits you best.

. Using the `@JavaScript` and `@HtmlImport` annotations.
+
*Example*: Importing HTML and JavaScript files into `HtmlComponent`.
+
[source,java]
----
@Tag("div")
@JavaScript("/js/script.js")
@HtmlImport("/html/htmlimport.html")
static class HtmlComponent extends Component implements HasText {
  // implementation omitted
}
----

* Both annotations are repeatable. Add one annotation for each file you need to add. 

. Using the `addHtmlImport(String url)` and `addJavaScript(String url)` methods from the `Page` class.
+
*Example*: Using the `addHtmlImport(String url)` and `addJavaScript(String url)` methods. to import HTML and JavaScript files. 
+
[source,java]
----
  private void addDependencies() {
    UI.getCurrent().getPage().addHtmlImport("/html/htmlimport.html");
    UI.getCurrent().getPage().addJavaScript("/js/script.js");
  }
----

See <<tutorial-ways-of-importing#,Storing and Loading Resources>> for more on storing your resources and configuring advanced resource loading. 
