---
title: Vaadin Spring Configuration
order: 5
layout: page
---

= Vaadin Spring Configuration

You can use many properties to configure your Vaadin Flow application. See, for example, the `com.vaadin.server.DeploymentConfiguration` and `com.vaadin.server.Constants` classes for the numerous property names. In addition to these properties, you can also set Spring properties as system properties. Spring configuration properties have the same names, but are prefixed with `vaadin.`.

== Using Spring Boot Properties

You can set properties for Spring Boot in your `application.properties` file. 

*Example*: Setting Spring URL mapping in `application.properties`.

[source,ini]
----
vaadin.urlMapping=/my_mapping/*
----
* By default, URL mapping is `/*`.

[NOTE]
An additional servlet, such as `/my_mapping/*`, is required to handle the frontend resources for non-root servlets.  The servlet can be defined in your application class. See this https://raw.githubusercontent.com/vaadin/flow-and-components-documentation/master/tutorial-servlet-spring-boot/src/main/java/org/vaadin/tutorial/spring/Application.java[`Application` class] for a example.

== Configuring Spring MVC Applications

If you use <<tutorial-spring-basic-mvc#,Spring MVC>>, and therefore the `VaadinMVCWebAppInitializer` subclass, you need to populate your configuration properties yourself.

*Example*: Setting configuration properties in a Spring MVC application. 

[source,java]
----
@Configuration
@ComponentScan
@PropertySource("classpath:application.properties")
public class MyConfiguration {

}
----
* The `application.properties` file is still used, but you can use any name and any property source.
