---
title: Binding Data to Forms
order: 1
layout: page
---

ifdef::env-github[:outfilesuffix: .asciidoc]
= Binding Data to Forms

A typical application lets the user fill out structured data and maybe also browse previously entered data.
The data that is being entered is typically represented in code as an instance of a business object (bean), for instance, a Person in an HR application.

Flow provides a `Binder` class that the developer can use to define how the values in a business object should be bound to the fields shown in the user interface.
`Binder` takes care of reading values from the business object and converting the data between the format expected by the business object and the format expected by the field.
The input entered by the user can also be validated, and the current validation status can be presented to the user in different ways.

The first step to binding fields for a form is to create a `Binder` and bind some input fields. There is only one `Binder` instance for each form and it is used for all fields in that form.

[source, java]
----
Binder<Person> binder = new Binder<>(Person.class);

TextField titleField = new TextField();

// Start by defining the Field instance to use
binder.forField(titleField)
  // Finalize by doing the actual binding to the Person class
  .bind(
    // Callback that loads the title from a person instance
    Person::getTitle,
    // Callback that saves the title in a person instance
    Person::setTitle);

TextField nameField = new TextField();

// Shorthand for cases without extra configuration
binder.bind(nameField, Person::getName, Person::setName);
----

When we have bound field components using our binder, we can use the binder to load values from a person into the field, let the user edit the values and finally save the values back into a person instance.

[source, java]
----
// The person to edit
// Would be loaded from the backend in a real application
Person person = new Person("John Doe", 1957);

// Updates the value in each bound field component
binder.readBean(person);

Button saveButton = new Button("Save",
  event -> {
    try {
      binder.writeBean(person);
      // A real application would also save the updated person
      // using the application's backend
    } catch (ValidationException e) {
      notifyValidationException(e);
    }
});

// Updates the fields again with the previously saved values
Button resetButton = new Button("Reset",
  event -> binder.readBean(person));
----

Every time `writeBean` is called, the data is validated and then copied from the UI to the business object. If the data is invalid a `ValidationException` that includes all errors in the data is thrown. That is why we need to put `writeBean` inside a try/catch block.

With these basic steps, we have defined everything that is needed for loading, editing and saving values for a form.

The above example uses Java 8 method references for defining how field values are loaded and saved. It is also possible to use a lambda expression instead of a method reference. You
can use this to call any method or to run additional commands in the callback:

[source, java]
----
// With lambda expressions
binder.bind(titleField,
        person -> person.getTitle(),
        (person, title) -> {
            person.setTitle(title);
            logger.info("setTitle: {}", title);
        });
----

== Binding Non-Modifiable Data

To bind a component to non-modifiable data we bind it with null value for the `setter`. For example:

[source, java]
----
TextField fullName = new TextField();
binder.forField(fullName).bind(Person::getFullName, null);
----

The Binder can only bind components that implement the `HasValue` interface e.g. TextField and ComboBox. If we want to bind other components, that does
not implement the `HasValue` interface, to non-modifiable data we should use the `ReadOnlyHasValue` helper class. For example, we can bind a `Label` to display
a person’s full name:

[source, java]
----
Label fullNameLabel = new Label();
ReadOnlyHasValue<String> fullName = new ReadOnlyHasValue<>(
        text -> fullNameLabel.setText(text));
binder.forField(fullName).bind(Person::getFullName, null);
----