---
title: Introduction to Web Components
order: 30
layout: page
---

== What are Web Components?

Web Components are components that comply with the Web Component's https://www.webcomponents.org/specs[specification]. 

The specification defines a collection of web standards that allow you to create new HTML tags with custom names that are reusable and fully encapsulate their functionality and styles. The standards are supported by all modern browsers.

The term "Web Components" (capitalized) is distinct from the term "web components" (non-capitalized) that refers to HTML elements like `input`, `select`, or `textarea` that are native browser web components. 

See https://www.webcomponents.org/introduction[WEBCOMPONENTS.ORG] for more. 


== Specifications

The Web Component's specification consist of four main standards [1] that can be used independently or together:

*  *Custom Elements*: A set of APIs to define new HTML elements and their functionality.
*  *Shadow DOM*: A set of APIs to provide encapsulation of the element's styles markup and functions, so that the Web Component remains "hidden" and separate from the rest of the DOM.
+
[NOTE]
+
Everything in the shadow DOM can still be viewed and accessed
* *ES Modules*: Defines standards for the inclusion and reuse of JavaScript documents in other JS documents. Enables modular Web Component development that aligns JavaScript application development standards. 
*  *HTML Template*: The `<template>` element allows you to input fragments of HTML that remain inert at page load, but can be instantiated at runtime.

[NOTE]
An *HTML Imports* specification was proposed at draft stage. It was not adopted after backlash from some modern browser vendors [2][3] and WebKit engineers [4]. This mechanism allows you to import and reuse custom components (or parts thereof) from an external source.  


== Vaadin and Web components

Vaadin provides and maintains a set of Web Components and corresponding Java APIs. 

To learn more about how Vaadin utilizes Web Components, see:

* https://vaadin.com/components[Vaadin Components]: A modern set of Web Components for business applications.
* <<integrating-a-web-component#,Integrating a Web Component>> into Vaadin.
* https://vaadin.com/directory[Vaadin Directory]: A list of curated and rated third-party Web Components.

== External links and references

[1] https://github.com/w3c/webcomponents/

[2] https://hacks.mozilla.org/2014/12/mozilla-and-web-components/

[3] https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports

[4] https://webkit.org/status/#feature-html-imports
