---
title: Loading from and Saving to Business Objects
order: 3
layout: page
---

= Loading From and Saving To Business Objects

Once your bindings are set up, you are ready to fill the bound UI components with data from your business objects. 

== Loading data to Binder

You can use the `reset()` method to read values from a business object instance into the UI components.


*Example*: Using the `reset()` method.

[source, typescript]
----

this.binder.reset(person);
----

Using `reset()` without a parameter will reset to the previously value, which is initially empty.

[source, typescript]
----
this.binder.reset();
----

== Saving data
You can get the value from the binder at any time using `binder.value`. The following
example shows how can you save the value form the binder to an Endpoint.

*Example*: Using the `binder.value` to get the value from the form.

[source, typescript]
----
this.viewEndpoint.save(binder.value);
----

Alternatively, you can use the `submitTo()` method to submit the value to a callback. Note the `submitTo()` is an asynchronous function, you can use `await` to wait for the result. The benefit of using `submitTo()`
is that submission failures are handled automatically, no need to do an explicit try-catch.

*Example*: Using the `submitTo()` method to submit to an endpoint method.

[source, typescript]
----
await this.binder.submitTo(viewEndpoint.savePerson);
----

