---
title: Binding Data to Client-Side Forms
order: 1
layout: page
---

= Binding Data to Client-Side Forms

Vaadin 17+ provides means for binding UI components in TypeScript form views. There is a client-side `Binder` class that is responsible for keeping the state of the form, the default and current values, and validation of the data.

The client-side `Binder` supports Java backend endpoints for loading and saving the form data, and reuses the metadata from Java Bean validation annotations for client-side validation.

== How to Bind Form Data

For example, let us consider a Java endpoint with methods for loading and saving a `Person` bean:

[source, java]
----
/**
 * A Vaadin endpoint for the person-view.ts form view.
 */
@Endpoint
public class PersonEndpoint {
    /**
     * Loads a Person to edit into the view.
     * @return default form data
     */
    public Person loadPerson() {
        // ...
    }

    /**
     * Saves the edited Person from the view.
     * @param person form data to save
     */
    public void savePerson(Person person) {
        // ...
    }
}
----

To bind data to a form, follow these steps in your `frontend/views/person/person-view.ts` client-side LitElement view:

. Import the `Binder` class, the `field` template directive from the `@vaadin/form` package. Import your `personEndpoint` data endpoint and the generated `PersonModel` from the `frontend/generated` folder:
+
[source, typescript]
----
import {Binder, field} from '@vaadin/form';

import * as personEndpoint from '../../generated/PersonEndpoint';
import PersonModel from '../../generated/com/example/application/PersonModel';
----

. Create a `Binder` instance for your view using generated `PersonModel`:
+
[source, typescript]
----
@customElement('person-form')
class PersonForm extends LitElement {
  // ...

  private binder = new Binder(this, PersonModel);

  // ...
}
----
+
The `PersonModel` here is generated alongside with a `Person` TypeScript data interface from the `Person.java` bean. It describes the structure of the data and the validation-related metadata for the client-side form binding.

. Bind the UI components in the template using the `...="${field()}"` syntax:
+
[source, typescript]
----
class PersonForm extends LitElement {
  // ...

  render() {
    return html`
      <vaadin-text-field
       label="Full name"
       ...="${field(this.binder.model.fullName)}"
      ></vaadin-text-field>
    `;
  }
}
----
+
In this example, `this.binder.model` is an instance of `PersonModel`.
+
[NOTE]
Models do not contain any actual data. Use `this.binder.value` or `this.binder.defaultValue` to access the actual current or default value of the form respectively.
