---
title: Upload
order: 6
layout: page
---

= Upload

// this seems to be a complex component that requires more information 

The `Upload` component allows the user to upload files. The component supports single or multiple-file uploads and drag and drop.

== Using Upload

=== Setting Maximum Files

You can limit the number of files that can be uploaded at a time using the  `setMaxFiles` method.

=== Defining a Receiver Instance

A `Receiver` instance should be specified to receive uploaded data.

*Example*: Simple `Receiver` instance that allows uploading of one file. 
[source, java]
----
FileBuffer fileBuffer = new FileBuffer();
Upload upload = new Upload(fileBuffer);
----

* The uploaded data is stored in a file on the file system. 
* You can get the data from the file using the `getInputStream()` method.

You can use a `MultiFileReceiver` to allow uploading of more than one file. 

*Example*: Using `MultiFileBuffer` 

[source, java]
----
MultiFileBuffer multiFileBuffer = new MultiFileBuffer();
Upload upload = new Upload(multiFileBuffer);
----

* The `MultiFileBuffer` class is a ready-made implementation of `MultiFileReceiver`.
* The data is stored in files on the file system and you can get the data using a file name and the `getInputStream(String)` method.

