---
title: Using Vaadin Components
order: 1
layout: page
---

= Using Vaadin Components

The Vaadin Platform includes a set of https://vaadin.com/components/browse[components], with server-side Java APIs, that you can use to build your UI.   

The components are included, together with Flow, as dependencies in platform.

The _vaadin-core_ module includes all open source components, such as TextField, Button and Grid. The _vaadin_ module extends this set with all officially supported components in Vaadin platform, like Vaadin Charts.

== Vaadin Platform Dependency

The components are part of the Vaadin platform and are included as dependencies, together with Flow. Each component has a Java API. 

Using the platform dependency (com.vaadin:vaadin) ensures that all available components, both open source and commercial, are included automatically. You are guaranteed to get compatible versions of both Flow and the components.

*Example*: Declaring the `vaadin.platform` dependency. 

[source,xml]
----
    <dependencies>
    <!-- other dependencies -->
    <!-- component dependency -->
    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin</artifactId>
        <version>${vaadin.platform.version}</version>
    </dependency>
</dependencies>
----

[NOTE]
It is possible to include components individually by declaring a dependency for each component. See below for an example.

The platform also includes theming for the components that you can edit to ensure the styling suits your UI. See <<../theme/using-component-themes#,Using Component Themes>> for more.

You can find additional prebuilt Web Components (with Java APIs) contributed by the Vaadin community in the https://vaadin.com/directory/search[Vaadin Directory.]

== Individual Component Dependencies

As an alternative to using the platform dependency, you can declare single components as dependencies.

https://www.webjars.org/ generates the Maven artifacts with pom.xml that specifies version ranges for jar's dependencies
instead of some particular version. This means that build results may differ from time to time because of the new libraries' versions released.
Vaadin provides a BOM (Bill Of Materials) that fixes all vaadin-related dependencies to a tested combination, so that the individual components can be added safely.

You need to add the `bom` and the relevant Flow component package, for example `vaadin-button-flow`, to your project dependencies.

*Example*: Adding the Button component in your `pom.xml` using Maven.

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-bom</artifactId>
            <version>${vaadin.platform.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <!-- other dependencies -->

    <!-- component dependency -->
    <dependency>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-button-flow</artifactId>
    </dependency>
</dependencies>
----
