---
title: Elevation
layout: page
---

= Lumo Elevation

// Needed to show embedded live previews
include::../themes-shared.asciidoc[opts=optional]


== Shadow

Shadows are used to indicate elements which are stacked on top of other elements in the UI.

++++
<content-preview class="block background-shade">
++++

[source, html]
----
<div class="box xs shadow">XS</div>
<div class="box s shadow">S</div>
<div class="box m shadow">M</div>
<div class="box l shadow">L</div>
<div class="box xl shadow">XL</div>

<custom-style>
  <style>
    .shadow.xs {
      box-shadow: var(--lumo-box-shadow-xs);
    }
    .shadow.s {
      box-shadow: var(--lumo-box-shadow-s);
    }
    .shadow.m {
      box-shadow: var(--lumo-box-shadow-m);
    }
    .shadow.l {
      box-shadow: var(--lumo-box-shadow-l);
    }
    .shadow.xl {
      box-shadow: var(--lumo-box-shadow-xl);
      width: calc(var(--lumo-size-xl) * 1.2);
      height: calc(var(--lumo-size-xl) * 1.2);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
== Cursor for clickable elements
++++
    <p>Use this property for elements that are clickable, such as buttons. That way, an application
      can easily decide which mouse cursor to use for them. Traditional web address links (anchors)
      should always use the <code>pointer</code> cursor (pointing hand).</p>

    <p>By default, Lumo uses the <code>default</code> cursor (arrow) for clickable elements.</p>

<content-preview class="block">
++++
[source,html]
----
<vaadin-button>Default</vaadin-button>
<vaadin-button class="pointer">Pointer</vaadin-button>

<custom-style>
  <style>
    .pointer {
      --lumo-clickable-cursor: pointer;
      cursor: var(--lumo-clickable-cursor);
    }
  </style>
</custom-style>
----
++++

</content-preview>

++++
== Custom properties
++++
  <content-preview class="block" hidesource raw>
    <h5>Shadow</h5>
    <p theme="font-size-s">The shadows use various <code>--lumo-shade</code> colors. Computed values are shown here instead of the declared values.</p>
    <dl class="custom-properties">
      <dt>--lumo-box-shadow-xs: <code>0 1px 4px -1px  hsla(214, 45%, 20%, 0.5)</code></dt>
        <dd>Elements closest to the application background, for example cards.</dd>
      <dt>--lumo-box-shadow-s: <code>0 2px 4px -1px  hsla(214, 53%, 23%, 0.16), 0 3px 12px -1px  hsla(214, 50%, 22%, 0.26)</code></dt>
        <dd>Tooltips, etc.</dd>
      <dt>--lumo-box-shadow-m: <code>0 2px 6px -1px  hsla(214, 53%, 23%, 0.16), 0 8px 24px -4px  hsla(214, 47%, 21%, 0.38)</code></dt>
        <dd>Contextual popups, such as select menus.</dd>
      <dt>--lumo-box-shadow-l: <code>0 3px 18px -2px  hsla(214, 53%, 23%, 0.16), 0 12px 48px -6px  hsla(214, 47%, 21%, 0.38)</code></dt>
        <dd>Elements that rise above above most elements in the UI, for example dialogs.</dd>
      <dt>--lumo-box-shadow-xl: <code>0 4px 24px -3px  hsla(214, 53%, 23%, 0.16), 0 18px 64px -8px  hsla(214, 47%, 21%, 0.38)</code></dt>
        <dd>Elements highest in the stacking order, for example notifications, which should be above all other content.</dd>
    </dl>

    <h5>Interaction</h5>
    <dl class="custom-properties">
      <dt>--lumo-clickable-cursor: <code>default</code></dt>
    </dl>
  </content-preview>
++++
