---
title: Overview
order: 1
layout: page
---

// The following source is in HTML because it's copied from https://github.com/vaadin/vaadin-lumo-styles/tree/master/demo as is
include::../themes-shared.asciidoc[]

= Lumo

Lumo is the default theme for Vaadin, which can be customized to fit your visual style requirements.

The core Lumo package defines the basic building blocks for component themes as CSS custom properties, also known as design tokens, such as colors, typography and other visual styles.

In addition to the custom properties, Lumo comes with a ready-made <<badges#,Badge>> component and a collection of <<icons#,icons>> which match the default Lumo visual style.


== Lumo Theme Editor

To quickly adjust most of the global styles of Lumo, you can use the https://demo.vaadin.com/lumo-editor/[Lumo theme editor].

The Lumo theme editor is not yet an officially supported tool and does not necessarily support the latest versions of Vaadin. You can still use the CSS it produces by copying them to the correct files in your project. Visit the Labs page to https://vaadin.com/labs/lumo-editor/[give feedback about the Lumo theme editor tool].


== Getting started

=== Install

Lumo comes bundled with Vaadin (including all individual components). If you need, you can also install the core Lumo package separately using https://www.npmjs.com[npm].

[source]
----
npm i @vaadin/vaadin-lumo-styles
----

=== Import and Include Style Sheets

The global style sheets, which define the global custom properties (a.k.a. design tokens) and define basic color and typography rules, are automatically included in your Vaadin app when you are using Lumo as your theme. excluding <<badges>> which needs to be imported and included explicitly.

You can import and include these style sheets manually if needed, for example if you are building a client-side only app.

[source,html]
----
<script type="module">
  import '@vaadin/vaadin-lumo-styles/color.js';
  import '@vaadin/vaadin-lumo-styles/sizing.js';
  import '@vaadin/vaadin-lumo-styles/spacing.js';
  import '@vaadin/vaadin-lumo-styles/style.js';
  import '@vaadin/vaadin-lumo-styles/typography.js';
  import '@vaadin/vaadin-lumo-styles/icons.js';
  import '@vaadin/vaadin-lumo-styles/badges.js';
</script>

<!-- Include the core style sheets in global scope (index.html) -->
<custom-style>
  <style include="lumo-color lumo-typography lumo-badge"></style>
</custom-style>

<!-- Include the style sheets in the local scope of a component -->
----

[NOTE]
See <<../../flow/theme/including-style-sheets#,Including style sheets>> for more information
