---
title: Typography
order: 2
layout: page
---

// The following source is in HTML because it's copied from https://github.com/vaadin/vaadin-lumo-styles/tree/master/demo as is
include::../themes-shared.asciidoc[]

= Typography

++++
    <p>Lumo defines a set of style modules and CSS custom properties you can use to apply a consistent typographic styles across your application.</p>

    <p>Import <code>typography.js</code> to use them.</p>
++++
[source,html]
----
<script type="module">
  import '@vaadin/vaadin-lumo-styles/typography.js';
</script>
----
== Style module
++++
    <p>Include the typography style module to easily apply basic typographic styles for any style scope. It will set the font family, font size and line height for the root element (<code>html</code> in the global scope), as well as specify header and link styles inside the style scope.</p>

++++
[source,html]
----
<!-- Add directly to index.html or use a separate HTML import -->
<custom-style>
  <style include="lumo-typography"></style>
</custom-style>
----
++++
<content-preview class="block" shady-disclaimer>
++++
[source,html]
----
<h1>Header 1</h1>
<h2>Header 2</h2>
<h3>Header 3</h3>
<h4>Header 4</h4>
<h5>Header 5</h5>
<h6>Header 6</h6>
<p>Plain text.</p>
<p><a href="">Link</a></p>
<p theme="font-size-s">Small size text.</p>
<p theme="font-size-xs">Extra small size text.</p>
----
++++
</content-preview>
++++
== Font family
++++
    <p>The system font stack is used by default: Segoe UI on Windows; Roboto on Android and Chrome OS; San Francisco on macOS and iOS; On other systems, Helvetica, Arial are used as fallbacks.</p>
    <p>You can apply or change the font family using the <code>--lumo-font-family</code> custom property.</p>
++++
[source,html]
----
<!-- Add directly to index.html or use a separate HTML import -->
<custom-style>
  <style>
    html {
      --lumo-font-family: "Open Sans", sans-serif;
    }
  </style>
</custom-style>
----

== Font size
++++
    <p>The following font sizes are available to use. <b>M is the standard size</b>, and is used by most elements by default.</p>

<content-preview class="block">
++++
[source,html]
----
<div class="font-size-xxxl">Font size XXXL</div>
<div class="font-size-xxl">Font size XXL</div>
<div class="font-size-xl">Font size XL</div>
<div class="font-size-l">Font size L</div>
<div class="font-size-m">Font size M</div>
<div class="font-size-s">Font size S</div>
<div class="font-size-xs">Font size XS</div>
<div class="font-size-xxs">Font size XXS</div>

<custom-style>
  <style>
    .font-size-xxxl {
      font-size: var(--lumo-font-size-xxxl);
    }
    .font-size-xxl {
      font-size: var(--lumo-font-size-xxl);
    }
    .font-size-xl {
      font-size: var(--lumo-font-size-xl);
    }
    .font-size-l {
      font-size: var(--lumo-font-size-l);
    }
    .font-size-m {
      font-size: var(--lumo-font-size-m);
    }
    .font-size-s {
      font-size: var(--lumo-font-size-s);
    }
    .font-size-xs {
      font-size: var(--lumo-font-size-xs);
    }
    .font-size-xxs {
      font-size: var(--lumo-font-size-xxs);
    }
  </style>
</custom-style>
----
++++
</content-preview>
++++
== Custom properties
++++
    <content-preview class="block" hidesource raw>
      <h5>Font family</h5>
      <dl class="custom-properties">
        <dt>--lumo-font-family: <code>-apple-system, BlinkMacSystemFont, "Roboto", "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"</code></dt>
      </dl>

      <h5>Font size</h5>
      <dl class="custom-properties">
        <dt>--lumo-font-size-xxxl: <code>2.5rem</code></dt>
        <dt>--lumo-font-size-xxl: <code>1.75rem</code></dt>
        <dt>--lumo-font-size-xl: <code>1.375rem</code></dt>
        <dt>--lumo-font-size-l: <code>1.125rem</code></dt>
        <dt>--lumo-font-size-m: <code>1rem</code></dt>
        <dt>--lumo-font-size-s: <code>0.875rem</code></dt>
        <dt>--lumo-font-size-xs: <code>0.8125rem</code></dt>
        <dt>--lumo-font-size-xxs: <code>0.75rem</code></dt>
      </dl>

      <h5>Line-height</h5>
      <dl class="custom-properties">
        <dt>--lumo-line-height-m: <code>1.625</code></dt>
        <dt>--lumo-line-height-s: <code>1.375</code></dt>
        <dt>--lumo-line-height-xs: <code>1.25</code></dt>
      </dl>
    </content-preview>
++++
